# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
        
    - name: Install Node&Hexo env
      run: |
        npm install
        npm install -g hexo
    
    - name: Build
      run: hexo g

    - name: Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: zsh2401
        server: dream.zsh2401.top
        port: ${{ secrets.SFTP_PORT }} 
        ssh_private_key: ${{ secrets.SFTP_PK }} 
        local_path: './public/*'
        remote_path: '/home/zsh2401/apps/dnmp/www/blog' #make sure if dir exist
        args: '-o ConnectTimeout=5'