# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
        
    - name: Install dependencies
      run: yarn
    
    - name: Build
      run: yarn hexo g

    - name: Deploy to Static Pages Server
      run: yarn deploy
      env:
        FULL_REPO: ${{ secrets.CODING_REPO }}

    - name: Deploy to SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: zsh2401
        server: dream.zsh2401.top
        port: ${{ secrets.SFTP_PORT }} 
        ssh_private_key: ${{ secrets.SFTP_PK }} 
        local_path: './public/*'
        remote_path: '/home/zsh2401/apps/dnmp/www/blog' #make sure if dir exist
        args: '-o ConnectTimeout=5'